# Generated by Django 5.0.14 on 2025-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(db_column='Restaurant_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('cuisine_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cuisine_Type', max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
                ('price_range', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Price_Range', max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact_Info', max_length=100, null=True)),
                ('availability', models.BooleanField(blank=True, db_column='Availability', null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
    ]
