# Generated by Django 5.0.14 on 2025-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.AutoField(db_column='Attraction_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('hours_of_operation', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Hours_Of_Operation', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Attraction',
                'managed': False,
            },
        ),
    ]
