# Generated by Django 5.0.14 on 2025-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.AutoField(db_column='Attraction_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('hours_of_operation', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Hours_Of_Operation', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Attraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField(blank=True, db_column='Entity_ID', null=True)),
                ('booking_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Booking_Type', max_length=50, null=True)),
                ('booking_date', models.DateField(blank=True, db_column='Booking_Date', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50, null=True)),
                ('total_cost', models.DecimalField(blank=True, db_column='Total_Cost', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('chatbot_id', models.AutoField(db_column='Chatbot_ID', primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Language', max_length=50, null=True)),
                ('availability', models.BooleanField(blank=True, db_column='Availability', null=True)),
                ('ai_model_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AI_Model_Type', max_length=100, null=True)),
                ('last_training_date', models.DateField(blank=True, db_column='Last_Training_Date', null=True)),
            ],
            options={
                'db_table': 'Chatbot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(db_column='Hotel_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
                ('price_range', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Price_Range', max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact_Info', max_length=100, null=True)),
                ('available_rooms', models.IntegerField(blank=True, db_column='Available_Rooms', null=True)),
            ],
            options={
                'db_table': 'Hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(db_column='Notification_ID', primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Message', null=True)),
                ('notification_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notification_Type', max_length=50, null=True)),
                ('sent_date', models.DateField(blank=True, db_column='Sent_Date', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='Payment_ID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(blank=True, db_column='Payment_Date', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Payment_Method', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(db_column='Recommendation_ID', primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField(blank=True, db_column='Entity_ID', null=True)),
                ('recommendation_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Recommendation_Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(db_column='Restaurant_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('cuisine_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cuisine_Type', max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
                ('price_range', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Price_Range', max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact_Info', max_length=100, null=True)),
                ('availability', models.BooleanField(blank=True, db_column='Availability', null=True)),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(db_column='Review_ID', primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField(blank=True, db_column='Entity_ID', null=True)),
                ('entity_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Entity_Type', max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comment', null=True)),
                ('review_date', models.DateField(blank=True, db_column='Review_Date', null=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='Room_ID', primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Room_Type', max_length=50, null=True)),
                ('price_per_night', models.DecimalField(blank=True, db_column='Price_Per_Night', decimal_places=2, max_digits=10, null=True)),
                ('availability', models.BooleanField(blank=True, db_column='Availability', null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
            ],
            options={
                'db_table': 'Room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(db_column='Tour_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Duration', max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('available_spots', models.IntegerField(blank=True, db_column='Available_Spots', null=True)),
            ],
            options={
                'db_table': 'Tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('info_id', models.AutoField(db_column='Info_ID', primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('transportation_options', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Transportation_Options', null=True)),
                ('travel_costs', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Travel_Costs', null=True)),
                ('travel_tips', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Travel_Tips', null=True)),
            ],
            options={
                'db_table': 'Travel_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(db_column='Weather_ID', primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('temperature', models.FloatField(blank=True, db_column='Temperature', null=True)),
                ('conditions', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Conditions', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Weather',
                'managed': False,
            },
        ),
    ]
