# Generated by Django 5.0.14 on 2025-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField(blank=True, db_column='Entity_ID', null=True)),
                ('booking_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Booking_Type', max_length=50, null=True)),
                ('booking_date', models.DateField(blank=True, db_column='Booking_Date', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50, null=True)),
                ('total_cost', models.DecimalField(blank=True, db_column='Total_Cost', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='Payment_ID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(blank=True, db_column='Payment_Date', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Payment_Method', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
    ]
